# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # --- Formatters (run first) ---
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  # --- Linters (run second) ---
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: ["--strict"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
